### PR TITLE
AppVeyor CI

### PR DESCRIPTION
**Pull request by davidpodhola**
Basic appveyor continous integration setup.
Appveyor still needs to be created on the master repository (see https://ci.appveyor.com/project/davidpodhola/fabel)

### CODE REVIEW

**Comment by davidpodhola** [comment]
appveyor is running tests too
ugly search&replace "fix" for https://github.com/fsharp/FSharp.Compiler.Service/issues/529

**Comment by alfonsogarciacaro** [comment]
Fantastic, thanks a lot for that! I gave Appveyor access to the master repo and it's working :) About the bug in FSharp.Compiler.Service, it seems they're already taking care of it so hopefully we can remove the hack soon.

**Comment by rneatherway** [comment]
This should be fixed in the just-released 2.0.0.6. Let me know how it goes.

**Comment by alfonsogarciacaro** [comment]
I updated FSharp.Compiler.Service, removed the hack and the AppVeyor build still works so it seems the problem is fixed :) Thanks a lot for your work, Robin!

**Comment by rneatherway** [comment]
Great!

**Pull request merged**
